Html handler
regular-project/hermes pull request #30
Opened 2021-09-14 16:23 UTC by Matster07

2021-09-14 23:27 UTC, darth-agent requested changes

2021-09-14 23:27 UTC, darth-agent commented on core/src/main/java/org/hermes/core/cache/MemoryCache.java
> +    @Scheduled(cron = "* */${hermes.cache.clear-interval} * *")
А для чего здесь * * * *, можно же полное выражение в кроне сразу прописывать, либо если хочется небольшие промежутки, то уже заиспользовать delay

2021-09-14 23:27 UTC, darth-agent commented on core/src/main/java/org/hermes/core/config/HermesConsumerConfig.java
> +import org.apache.avro.specific.SpecificRecord;
Может лучше дадим ей более понятное название, пока SpecificRecord выглядит как неопознанный объект

2021-09-14 23:27 UTC, darth-agent commented on core/src/main/java/org/hermes/core/extraction/HermesEgressRecordCacheable.java
> +        return Objects.equals(
У нас вроде есть Lombook, давай его сюда сразу подключим

2021-09-14 23:27 UTC, darth-agent commented on core/src/main/java/org/hermes/core/service/HermesConsumerService.java
> +        this.executorService = Executors.newCachedThreadPool();
Не уверен, что newCachedThreadPool хорошее решение для контроля нагрузки, лучше в случае нехватки кол-ва потоков для обработки выставить ExecutorService в prometheus и масштабироваться по нему, соответсвенно лучше заменить на fixedThreadPool

2021-09-14 23:27 UTC, darth-agent commented on html-handler/src/main/resources/application.yml
> +      topic: analyzer-service
В репе лучше все специфические моменты поменять на общие названия, я так понял analyzer-service - это уже конкретно топик в твоей системе

2021-09-14 23:27 UTC, darth-agent commented on html-handler/src/test/java/org/hermes/htmlhandler/HtmlCustomParentTypeTest.java
> +        String data = "";
Можно так упростить:

Stream<String> lines = Files.lines(path);
String data = lines.collect(Collectors.joining("\n"));
lines.close();

2021-09-14 23:27 UTC, darth-agent commented on html-handler/src/test/java/org/hermes/htmlhandler/HtmlDataParentTypeTest.java
> +        URL url = this.getClass().getResource("/" + DATA_FILE_NAME);
Чуть выше писал, хорошо бы вынести это в утилку, чтобы больше не повторять

2021-09-14 23:27 UTC, darth-agent commented on json-handler/src/test/java/org/hermes/jsonhandler/JsonDataHandlerTest.java
> +//    @Test
Точно нужны закомментированные тесты?

2021-09-14 23:27 UTC, darth-agent commented on producer-initializer/src/main/java/org/hermes/schemainitializer/service/HermesProducerService.java
> +                System.out.println("Sent message with offset=[" + result.getRecordMetadata().offset() + "]");
Нужно поменять на логи

2021-09-14 23:27 UTC, darth-agent commented on producer-initializer/src/main/java/org/hermes/schemainitializer/service/HermesProducerService.java
> +                System.out.println("Unable to send message due to : " + ex.getMessage());
Нужно поменять на логи

2021-09-15 08:20 UTC, Matster07 commented on core/src/main/java/org/hermes/core/cache/MemoryCache.java
> +    @Scheduled(cron = "* */${hermes.cache.clear-interval} * *")
Как вариант. Единственное я выпилил memoryCache вообще в использовании и оставил просто, как альтернативу. Нужно добавить default значение очистки вне конфига и уже если человек все-таки захочет использовать memoryCache, у него будет зарезервировано эта настройка

2021-09-15 08:22 UTC, Matster07 commented on core/src/main/java/org/hermes/core/config/HermesConsumerConfig.java
> +import org.apache.avro.specific.SpecificRecord;
Это общий интерфейс для всех Avro форматов, чтобы в Core мы не были привязаны к конкретному формату протокола, а в реализациях использовали уже подходящие реализации HtmlIngress, JsonIngress и тд

2021-09-15 08:22 UTC, Matster07 commented on core/src/main/java/org/hermes/core/extraction/HermesEgressRecordCacheable.java
> +        return Objects.equals(
Кк

2021-09-15 08:22 UTC, Matster07 commented on core/src/main/java/org/hermes/core/service/HermesConsumerService.java
> +        this.executorService = Executors.newCachedThreadPool();
Согласен

2021-09-15 08:23 UTC, Matster07 commented on html-handler/src/main/resources/application.yml
> +      topic: analyzer-service
кк

2021-09-15 08:23 UTC, Matster07 commented on html-handler/src/test/java/org/hermes/htmlhandler/HtmlCustomParentTypeTest.java
> +        String data = "";
Кк

2021-09-15 08:23 UTC, Matster07 commented on html-handler/src/test/java/org/hermes/htmlhandler/HtmlDataParentTypeTest.java
> +        URL url = this.getClass().getResource("/" + DATA_FILE_NAME);
Кк

2021-09-15 08:25 UTC, Matster07 commented on json-handler/src/test/java/org/hermes/jsonhandler/JsonDataHandlerTest.java
> +//    @Test
Тесты 100% нужны и будут, нужен был готовый коммит для разрабов

2021-09-15 08:25 UTC, Matster07 commented on producer-initializer/src/main/java/org/hermes/schemainitializer/service/HermesProducerService.java
> +                System.out.println("Sent message with offset=[" + result.getRecordMetadata().offset() + "]");
Кк

2021-09-15 08:25 UTC, Matster07 commented on producer-initializer/src/main/java/org/hermes/schemainitializer/service/HermesProducerService.java
> +                System.out.println("Unable to send message due to : " + ex.getMessage());
Кк

2023-03-01 15:37 UTC, WhoIsDarth approved these changes

2023-03-01 15:42 UTC, merged